# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.1

pipelines:          
  default:
    - step:
        name: Build and Test
        script:
          - npm install
          - npm run build
        artifacts:
          - build/**
  branches:        
    release:
      - step:
          name: Clone to release
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy to release
          deployment: staging
          trigger: manual
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.1
              variables:
                AWS_ACCESS_KEY_ID: "----------"
                AWS_SECRET_ACCESS_KEY: "----------"
                AWS_DEFAULT_REGION: "us-east-1"
                S3_BUCKET: "hh-labhero-test"
                LOCAL_PATH: "build"
                ACL: "public-read"
                CACHE_CONTROL: "max-age=3600"
                EXTRA_ARGS: "--follow-symlinks"
    master:
      - step:
          name: Clone to production
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy to production
          deployment: production
          trigger: manual
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.1
              variables:
                AWS_ACCESS_KEY_ID: "----------"
                AWS_SECRET_ACCESS_KEY: "----------"
                AWS_DEFAULT_REGION: "us-east-1"
                S3_BUCKET: "hh-labhero-app"
                LOCAL_PATH: "build"
                ACL: "public-read"
                CACHE_CONTROL: "max-age=3600"
                EXTRA_ARGS: "--follow-symlinks"