steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  timeout: 300s
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  timeout: 300s
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['gcloud', 'auth', 'activate-service-account', '--key-file', '']
