export const CLR_SEL_EXAMS = 'CLR_SELECTED_EXAMS';
export const CLR_PERSONAL_INFO = 'CLR_PERSONAL_INFO';
export const CLR_OTHER_INFO = 'CLR_OTHER_INFO';
export const CLR_SEARCHED_NAME = 'CLR_SEARCHED_NAME';
export const CLR_SEARCHED_ID = 'CLR_SEARCHED_ID';
export const CLR_REQUEST_ID = 'CLR_REQUEST_ID'
export const CLR_STEP_PROGRESS = 'CLR_STEP_PROGRESS';



