export const initialModules = [
  {
    moduleID: 1,
    moduleName: 'DASHBOARD',
    view: true,
    create: false,
    edit: false,
  },
  {
    moduleID: 2,
    moduleName: 'REQUEST',
    view: true,
    create: true,
    edit: true,
    print: true,
  },
  {
    moduleID: 3,
    moduleName: 'PLHEBO',
    view: true,
    create: false,
    edit: false,
    print: true,
  },
  {
    moduleID: 4,
    moduleName: 'RESULT',
    view: true,
    create: true,
    edit: true,
    print: true,
  },
  {
    moduleID: 5,
    moduleName: 'PATIENT DEMOGRAPHICS',
    view: true,
    create: false,
    edit: true,
    print: false,
  },
  {
    moduleID: 6,
    moduleName: 'SETTINGS',
    view: true,
    create: true,
    edit: true,
    print: true,
  },
];
